# Dockerfile.backend

FROM golang:1.26.4-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o backend ./cmd/tests

FROM alpine:3.20

WORKDIR /app

COPY --from=build /app/backend /app/backend

EXPOSE 9000

CMD ["/app/backend"]